### ISSUE TITLE
Embed in a structure or object field in K3

### ISSUE THREAD

**Issue by malvese** [sylvainjule/kirby-embed#26]
I have an issue when I use Embed in a structure field in Kirby 3. Once I add a video, the whole structure field is replaced by this error message "Cannot read properties of undefined (reading '$urls')":

![image](https://github.com/user-attachments/assets/2c35221b-0ae0-4b81-9f2b-b100b34c0587)

The field still works on the front end, I can fetch info and diplay the video, but can no longer edit the structure in the panel.
I tried with an Object field instead for the sake of testing, and have the same issue.

Kirby version is 3.10.11, Embed is 1.1.2.

I also tried with a fresh Starterkit install, with only the embed plugin installed, and could reproduce it by adding this to an existing blueprint :

```
fields:
  videos:
    label: Vidéos
    type: structure
    fields:
      videosource:
        label: Vidéo
        type: embed
```

In Kirby 4 it works fine, but I cant upgrade this particular site right now.
