### ISSUE TITLE
Preview does not update when used within Structure field

### ISSUE THREAD

**Issue by jamiehunterdesign** [sylvainjule/kirby-embed#6]
```
videos:
  type: structure
  fields:
    name:
      type: text
    video:
      type: embed
```
When using the arrows to navigating through a structure field in the panel, the video preview does not update to show the correct video despite the URL in the field changing.
